### ISSUE TITLE
[DX-323] when server.js errors, getData doesn't pass that on, it has a different runtime error.

### ISSUE THREAD

**Issue by dipunm** [opencomponents/oc-template-react#102]
![image](https://user-images.githubusercontent.com/5099980/34259499-61985400-e65a-11e7-8261-5a3540afef57.png)
As shown, I had a discovery related error, but in JS, it complained that data was undefined. I expect to see an error passed back in this situation.

**Comment by nickbalestra** [comment]
@dipunm : are you correctly handling errors in the server.js I immagine?

**Comment by dipunm** [comment]
@nickbalestra Yes. I started looking into fixing this, there are a few notes:

1. in react-template, when there is an error, there is no data, so we need to ensure we don't try to read properties on that before calling the callback.

2. the real issue is still in the oc-browser-client: the getData function doesn't check for errors using: `e[0].response.error`.

3. `e[0].response.error` is just a string, not very useful, so where possible, we should send `e[0].response.details` instead, `e[0].response.error` is always there, I haven't found a scenario where `e[0].response.details` isn't there, but in terms of readability, `details` isn't as obvious as `error` so I suggest when doing the if check, using `error`.

4. Inside details, there is another property `originalError` which is usually what we want. HOWEVER: when server.js sends an `Error` object (`callback(new Error('hello world'));`) that property is an empty object and the information seems to be on the outer object. I don't know enough about why this is the way it is, so I figured I'd post it here because I don't know what best to do in this situation. I think it warrants a discussion.

**Comment by nickbalestra** [comment]
Thanks for the detailed breakdown!
Definitely adding a ticket to solve the bug asap.

**Comment by dipunm** [comment]
![image](https://user-images.githubusercontent.com/5099980/34268946-820e3504-e67a-11e7-9850-79e24a24175b.png)
![image](https://user-images.githubusercontent.com/5099980/34269076-f0c03358-e67a-11e7-89df-6d0015f18fd6.png)

See attached images to show what I did before I stopped... I was working with a minified version of oc-client so `e` above is actually `apiResponse` unminified.

**Comment by matteofigus** [comment]
Closing as this should be fixed with `oc@0.42.15`

**Comment by nickbalestra** [comment]
Should be fixed with in `oc-template-react-compiler@3.1.2`
