### ISSUE TITLE
postcss-loader throws error of "TypeError: Cannot read property 'postcss' of null"

### ISSUE THREAD

**Issue by themoch** [opencomponents/oc-template-react#109]
when using postcss-loader to compile css-modules the following error is thrown on styles.css:

`Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'postcss' of null`

# style.css
@value primary, bgColor from './colors.css';

.container {
  background-color: bgColor;
}

# colors.css
@value primary: #BF4040;
@value bgColor: #00f;

**Comment by nickbalestra** [comment]
Awesome, thanks @themoch!
Can you add something similar to the example you pointed above within the [component we use for acceptance tests](https://github.com/opencomponents/oc-template-react/tree/master/acceptance-components/react-app)? So that we cover this case?

**Comment by matteofigus** [comment]
I also think @dipunm had a similar issue using the latest version of the oc-template-react

**Comment by themoch** [comment]
@nickbalestra I will have an update shortly

**Comment by nickbalestra** [comment]
Thank you again @themoch , published as `oc-template-react-compiler@3.1.1`
