### ISSUE TITLE
Unable to see component in IE 11

### ISSUE THREAD

**Issue by makahoshi** [opencomponents/oc-template-react#127]
The template.js file includes template literals (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) preventing it from rendering in IE 11.

http://myregistry/mycomponent/1.0.0/template.js
var oc=oc||{};oc.components=oc.components||{};oc.components['XXXX']=function(model){ return `<div id="oc-reactRoot-

**Comment by nickbalestra** [comment]
Thank you for reporting this @makahoshi !
Would you like to attempt a PR to fix this ? I would love to help if you need anything. I think we might want to transpile [that](https://github.com/opencomponents/oc-template-react/blob/master/packages/oc-template-react-compiler/lib/viewTemplate.js#L8) , while at the moment we simply [compress](https://github.com/opencomponents/oc-template-react/blob/master/packages/oc-template-react-compiler/lib/compileView.js#L87) it

**Comment by matteofigus** [comment]
I also think that for the time being we could just avoid the string literal to get a quick fix out, and then get that thingy transpiled as second step?

**Comment by nickbalestra** [comment]
@makahoshi should be fixed with the `oc-template-react-compiler@3.2.` let me know if that solves it!
