### ISSUE TITLE
[DX-413] CSS issues when Server-Side-Rendering since 4.0.1

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/oc-template-react#155]
**Description:**
As reported on Gitter: 

When rendering server-side the page flickers from no-style to being styled when the client executes oc.addStylesToHead, meaning that there won't be any styles provided on SSR,(with javascript off the component is indeed never styled.)

cc @kmcrawford @themoch

**Comment by themoch** [comment]
Also, 

When comments exist in the imported CSS it breaks with `Uncaught SyntaxError: Invalid or unexpected token` during `oc.addStylesToHead`

**Comment by matteofigus** [comment]
I vote for going back to `<style>` - if you need to move the style on the client-side, you can move it via JS by yourself - Let's talk about this with @Kimtaro

**Comment by nickbalestra** [comment]
Im of the same idea as @matteofigus as its a safe, universal default

**Comment by nickbalestra** [comment]
#157 address this, with a nice little add, we emit an oc-event when the script tag is going to be appended on page, passing css string to the eventHandler, so if you need you can do things there
