### ISSUE TITLE
When adding Unicode references in styles.css the Unicode is mutated after packaging

### ISSUE THREAD

**Issue by themoch** [opencomponents/oc-template-react#180]
# Steps to reproduce

1. Create new OC with oc-template-react
2. Open `styles.css`
3. Paste in: `.myClassA {content: "\e901";}`
4. `oc package`
5. Observe in `_package/styles.css` that the content attribute is now `\E901`

This breaks the use of font-icons and does not allow them to be used in OC.

**Comment by themoch** [comment]
@matteofigus @nickbalestra Any further thoughts on this? 

post-css and css-modules independently compile correctly.  This seems to be an issue with the oc-template-react-compiler and not the post-css tools used.

**Comment by kmcrawford** [comment]
I took a few minutes to look into this.

I removed the block from the webpackConfigurator.js and the content remained "\e901".   So I believe the issue is with the `css-loader`.

https://github.com/opencomponents/oc-template-react/blob/c463506157985918fbe70bc88112384d5e5850fa/packages/oc-template-react-compiler/lib/to-abstract-base-template-utils/webpackConfigurator.js#L20-L28

**Comment by themoch** [comment]
@kmcrawford when stepping through the code it makes it's way through `css-loader` to `postcss` and then in there it gets mutated after making a call to `lazy-result`.  this call is passed with a config object.  

A more detailed example can be found here:
https://gitter.im/postcss/postcss?at=5ac38d2cbb1018b37a54a50b

**Comment by matteofigus** [comment]
I remember an issue related to this. Is this related to this? 
https://github.com/opencomponents/oc-template-react/blob/b161f51ef1d04194326850ab4f45f33e80080e92/packages/oc-template-react-compiler/lib/compileView.js#L70

@Kimtaro @nickbalestra

**Comment by kmcrawford** [comment]
@matteofigus I don't think that's the issue.
I put a ` console.log('css: ', data.build['main.css'].toString());`  before that line calling fontFamilyUnicodeParser and can see that it is incorrect there.

**Comment by themoch** [comment]
Closing this issue.  After multiple deep dives it appears to be an issue with post-css.   Thanks for all the feedback and help.
