### ISSUE TITLE
IE11 Rendering Issue in Production

### ISSUE THREAD

**Issue by justinelam** [opencomponents/oc-template-react#263]
Getting this error in IE11 in production-only:

```
SCRIPT438: Object doesn't support property or method 'repeat'
File: react-dom.production.min.js, Line: 126, Column: 505
```
We're importing`babel-polyfill` in our first line of our app.js, but it looks like react-dom is being loaded before us.  Is there any way of loading `babel-polyfill` before anything else without having to add a script tag to the page?

**Comment by matteofigus** [comment]
@justinelam I am not sure babel-polyfill has the repeat polyfill, and I'm not sure repeat is used in react-dom. Is that in your component? In that case, I think you should be able to import the polyfill in your component and that should do: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Polyfill
