### ISSUE TITLE
Correct method for using postcss

### ISSUE THREAD

**Issue by autr** [opencomponents/oc-template-react#320]
Hello, I see in the docs that postcss is supported by this template, but cannot see a working example of a best practice using it. Plugins are added by an array within the "oc" object, like so;

```
{
  "name": "my-test-widget",
  "description": "",
  "version": "1.0.0",
  "oc": {
    "files": {
      "data": "server.js",
      "template": {
        "src": "app.js",
        "type": "oc-template-react"
      }
    },
    "parameters": {
      "name": {
        "default": "World",
        "description": "Your name",
        "example": "Jane Doe",
        "mandatory": false,
        "type": "string"
      }
    },
    "minify": false,
    "plugins": ["postcss-extend", "postcss-import"]
  },
  "devDependencies": {
    "oc-template-react-compiler": "5.1.4"
  }
}

```

But the CSS does not seem to be processed? I am getting a error

` throw new Error(strings.errors.cssNotValid());`

From oc-minify-file

**Comment by matteofigus** [comment]
Hi @autr, the template already takes care of using some post-css templates as specified in the [README](https://github.com/opencomponents/oc-template-react#features). If you want to add extra postcss plugins, you need to fork the whole repo and make a new template by yourself, and then allow all the components to use that template. The goal is to have a consistent way to make and bundle components, so it is not allowed to configure that on a component-by-component base, you rather do it once on the template. Hopefully, that makes sense - that's the goal of each template.
