### ISSUE TITLE
Installing oc-template-react to the registry

### ISSUE THREAD

**Issue by ChennyBaBy** [opencomponents/oc-template-react#418]
Hi Hi~! I'm struggling to understand how to install this on the registry side, I've tried sticking `templates: [require('oc-template-react')]` into the registry config but it's crashing the registry saying the components-details file is not valid. Is there a bit more info on how to implement this on the registry side ?

Thanks

**Comment by matteofigus** [comment]
Hi @ChennyBaBy that seems correct to me.
Have you tried running the registry without the react template? The component-details error sounds unrelated, more on the storage spectrum. Which storage are you using? S3?

**Comment by ChennyBaBy** [comment]
it turns out i was missing the jade template too in the registry.
